
export enum AuthErrorCode {
  // 401 Unauthorized
  TOKEN_MISSING = 'TOKEN_MISSING',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED',
  OAUTH_LOGIN_FAILED = 'OAUTH_LOGIN_FAILED',
  OAUTH_EMAIL_NOT_VERIFIED = 'OAUTH_EMAIL_NOT_VERIFIED',
  OAUTH_ACCOUNT_MISMATCH = 'OAUTH_ACCOUNT_MISMATCH',

  // 403 Forbidden
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  WRONG_AUDIENCE = 'WRONG_AUDIENCE',
  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',
  PROFILE_INACTIVE = 'PROFILE_INACTIVE',
  KINE_INACTIVE = 'KINE_INACTIVE',
  PROFILE_ACTIVATION_ADMIN_ONLY = 'PROFILE_ACTIVATION_ADMIN_ONLY',
  OWN_PATIENT_ONLY = 'OWN_PATIENT_ONLY',

  // 400 Bad Request — DTO validation
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INVALID_QUERY_PARAM = 'INVALID_QUERY_PARAM',
  INVALID_PROFILE_TYPE = 'INVALID_PROFILE_TYPE',
  ADMIN_REQUIRES_SYSTEM_ROLE = 'ADMIN_REQUIRES_SYSTEM_ROLE',
  KINE_NO_CABINET = 'KINE_NO_CABINET',
  KINE_OWNS_CABINET = 'KINE_OWNS_CABINET',

  // 400 Bad Request — multi-profile header
  PROFILE_HEADER_MISSING = 'PROFILE_HEADER_MISSING',
  PROFILE_ID_INVALID = 'PROFILE_ID_INVALID',
  KINE_ID_REQUIRED = 'KINE_ID_REQUIRED',
  KINE_ID_INVALID = 'KINE_ID_INVALID',
  PATCH_EMPTY = 'PATCH_EMPTY',
  UNIQUE_CODE_REQUIRED = 'UNIQUE_CODE_REQUIRED',

  // 400 Bad Request — reset-password flow
  CODE_INVALID = 'CODE_INVALID',
  CODE_EXPIRED = 'CODE_EXPIRED',
  CODE_TOO_MANY_ATTEMPTS = 'CODE_TOO_MANY_ATTEMPTS',
  RESET_TOKEN_INVALID = 'RESET_TOKEN_INVALID',
  PASSWORD_SAME_AS_OLD = 'PASSWORD_SAME_AS_OLD',

  // 400 Bad Request — registration / invitation
  JUSTIFICATIF_REQUIRED = 'JUSTIFICATIF_REQUIRED',
  STUDENT_JUSTIFICATIF_REQUIRED = 'STUDENT_JUSTIFICATIF_REQUIRED',
  PROFESSIONAL_NUMBER_REQUIRED = 'PROFESSIONAL_NUMBER_REQUIRED',
  PROFESSIONAL_NUMBER_FORBIDDEN = 'PROFESSIONAL_NUMBER_FORBIDDEN',
  FIELD_NOT_APPLICABLE = 'FIELD_NOT_APPLICABLE',
  INVITATION_EXPIRED = 'INVITATION_EXPIRED',
  INVITATION_NOT_KINE = 'INVITATION_NOT_KINE',
  REJECTION_REASON_REQUIRED = 'REJECTION_REASON_REQUIRED',

  // 400 Bad Request — file upload
  FILE_TYPE_NOT_ALLOWED = 'FILE_TYPE_NOT_ALLOWED',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',

  // 404 Not Found
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PATIENT_NOT_FOUND = 'PATIENT_NOT_FOUND',
  KINE_NOT_FOUND = 'KINE_NOT_FOUND',
  ADMIN_NOT_FOUND = 'ADMIN_NOT_FOUND',
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  MODULE_NOT_FOUND = 'MODULE_NOT_FOUND',
  PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND',
  ACTION_NOT_FOUND = 'ACTION_NOT_FOUND',
  CABINET_NOT_FOUND = 'CABINET_NOT_FOUND',

  // 409 Conflict
  EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED',
  ACCOUNT_ALREADY_EXISTS = 'ACCOUNT_ALREADY_EXISTS',
  PROFILE_ALREADY_EXISTS = 'PROFILE_ALREADY_EXISTS',
  INVITATION_ALREADY_USED = 'INVITATION_ALREADY_USED',
  INVITATION_ACCOUNT_MISMATCH = 'INVITATION_ACCOUNT_MISMATCH',
  PROFESSIONAL_NUMBER_ALREADY_USED = 'PROFESSIONAL_NUMBER_ALREADY_USED',
  ROLE_SYSTEM_PROTECTED = 'ROLE_SYSTEM_PROTECTED',
  ACTION_SLUG_ALREADY_EXISTS = 'ACTION_SLUG_ALREADY_EXISTS',
  MODULE_SLUG_ALREADY_EXISTS = 'MODULE_SLUG_ALREADY_EXISTS',
  PERMISSION_CODE_ALREADY_EXISTS = 'PERMISSION_CODE_ALREADY_EXISTS',
  ROLE_SLUG_ALREADY_EXISTS = 'ROLE_SLUG_ALREADY_EXISTS',
  DUPLICATE_KEY = 'DUPLICATE_KEY',

  // 429 Too Many Requests
  RATE_LIMITED = 'RATE_LIMITED',

  // 501 Not Implemented
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
}
