
export enum CaslAction {
  MANAGE = 'MANAGE', 
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',

  ASSIGN = 'ASSIGN',
  EXPORT = 'EXPORT',
  SCHEDULE = 'SCHEDULE',
  IMPORT = 'IMPORT',
  BULK_ACTION = 'BULK_ACTION',
  MANAGE_STATUS = 'MANAGE_STATUS',
}
